<?php

/**
 * BaseUniqueId
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $stub
 * @property string $project_name
 * @property string $access_key
 * 
 * @method string   getStub()         Returns the current record's "stub" value
 * @method string   getProjectName()  Returns the current record's "project_name" value
 * @method string   getAccessKey()    Returns the current record's "access_key" value
 * @method UniqueId setStub()         Sets the current record's "stub" value
 * @method UniqueId setProjectName()  Sets the current record's "project_name" value
 * @method UniqueId setAccessKey()    Sets the current record's "access_key" value
 * 
 * @package    uniqueid
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUniqueId extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unique_id');
        $this->hasColumn('stub', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('project_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('access_key', 'string', 36, array(
             'type' => 'string',
             'length' => 36,
             ));

        $this->option('symfony', array(
             'form' => true,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}