<?php

/**
 * UniqueIdTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UniqueIdTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UniqueIdTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UniqueId');
    }
}