UniqueId:
  options:
    symfony:
      form: true
      filter: false
  columns:
    stub:
      type: string(255)
      unique: true
    project_name:
      type: string(255)
    access_key:
      type: string(36)
